export const metadata = {
  title: "auth",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="h-full flex justify-center items-center">{children}</main>
  )
}
