import type { Metadata } from "next"
import { getCurrentProfile } from "@/actions/profileActions"
import { getServerById, getServersByProfileId } from "@/actions/serverActions"
import ServerSideBar from "@/components/ServerSideBar/ServerSideBar"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
  title: "Server Name",
  description: "Generated by create next app",
}

type ServerLayoutProps = {
  children: React.ReactNode
  params: { serverId: string }
}

async function ServerLayout({ children, params }: ServerLayoutProps) {
  const serverId = params.serverId

  // cheking if user is logged in
  const profile = await getCurrentProfile()
  if (!profile) return redirect(`/`)

  // checking is server is found
  const server = await getServerById(serverId)
  if (!server) return redirect(`/servers`)

  // getting all user's servers
  const userServers = await getServersByProfileId(profile.id)
  if (!userServers) return redirect(`/`)

  // checking if user is currently on this server
  const isUserOnServer = userServers.find(
    (userServer) => userServer.id === server.id
  )
  if (!isUserOnServer) return null

  return (
    <div className="flex w-full">
      <ServerSideBar serverId={serverId} />
      <section className="h-full w-full">{children}</section>
    </div>
  )
}

export default ServerLayout
