import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Server name",
  description: "Generated by create next app",
}

function ServerPage() {
  return <div>Server</div>
}

export default ServerPage
