"use client"
import type { Metadata } from "next"
import { useParams } from "next/navigation"

export const metadata: Metadata = {
  title: "Server name",
  description: "Generated by create next app",
}

function ServerPage() {
  const params = useParams()
  const serverId = params.serverId

  return <div>{serverId}</div>
}

export default ServerPage
