import type { Metadata } from "next"
import NavigationSideBar from "@/components/NavigationSideBar/NavigationSideBar"
import { getCurrentProfile } from "@/actions/profileActions"
import { getServersByProfileId } from "@/actions/serverActions"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
  title: "Servers",
  description: "Generated by create next app",
}

type ServersLayoutProps = {
  children: React.ReactNode
}

export default async function ServersLayout({
  children,
}: ServersLayoutProps) {

  const profile = await getCurrentProfile()
  if (!profile) return redirect(`/`)

  const servers = await getServersByProfileId(profile.id)
  if (!servers) return redirect(`/`)

  return (
    <main className="flex h-full">
      <NavigationSideBar servers={servers} />
      {children}
    </main>
  )
}
