import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getCurrentProfile } from "@/actions/profileActions";
import { getServersByProfileId } from "@/actions/serverActions";
import { redirectToSignIn } from "@clerk/nextjs";
import NavigationSideBar from "@/components/NavigationSideBar/NavigationSideBar";

export const metadata: Metadata = {
  title: "Servers",
  description: "Generated by create next app",
};

type ServersLayoutProps = {
  children: React.ReactNode;
};

export default async function ServersLayout({ children }: ServersLayoutProps) {
  const profile = await getCurrentProfile();
  if (!profile) return redirectToSignIn();

  const servers = await getServersByProfileId(profile.id);
  if (!servers) return redirect("/");

  return (
    <main className="flex h-full">
      <NavigationSideBar servers={servers} />
      {children}
    </main>
  );
}
