import "./global.css"
import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"

const font = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <body className={`h-full ${font.className}`}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
