import type { Metadata } from "next"
import { redirect } from "next/navigation"
import { getCurrentProfile } from "@/actions/profileActions"
import { redirectToSignIn } from "@clerk/nextjs"
import ConversationsSideBar from "@/components/ConversationsSideBar/ConversationsSideBar"
import { getConversations } from "@/actions/conversationActions"
import { getServersByProfileId } from "@/actions/serverActions"
import NavigationSideBar from "@/components/NavigationSideBar/NavigationSideBar"

export const metadata: Metadata = {
  title: "Direct Messages",
  description: "Generated by create next app",
}

type ServersLayoutProps = {
  children: React.ReactNode
}

export default async function ConversationsLayout({
  children,
}: ServersLayoutProps) {
  const profile = await getCurrentProfile()
  if (!profile) return redirectToSignIn()

  const conversations = await getConversations(profile.id)
  if (!conversations) return redirect("/servers")

  const servers = await getServersByProfileId(profile.id)
  if (!servers) return redirect("/")

  return (
    <main className="flex h-full w-full">
      <NavigationSideBar servers={servers} />
      <ConversationsSideBar profile={profile} conversations={conversations} />
      {children}
    </main>
  )
}
